name: Code Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
    # Checkout just the .github/scripts/code_review.py from main branch
      - name: Checkout .github/scripts from main
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: main
          path: main_dotgithub
          sparse-checkout: |
            .github/scripts/code_review.py
          sparse-checkout-cone-mode: false    

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: Run Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main_dotgithub/scripts/code_review.py
